name: DevSecOps CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v4

      - name: Prijava na github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend image
        run: docker build --target production -t ghcr.io/${{ github.repository_owner }}/projekt-frontend:latest ./frontend

      - name: Trivy (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/projekt-frontend:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push frontend image na GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/projekt-frontend:latest

      - name: Build API image
        run: docker build --target production -t ghcr.io/${{ github.repository_owner }}/projekt-api:latest ./api

      - name: Trivy (API)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/projekt-api:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Push API image na GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/projekt-api:latest

      - name: Build worker image
        run: docker build --target production -t ghcr.io/${{ github.repository_owner }}/projekt-worker:latest ./worker

      - name: Trivy (Worker)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/projekt-worker:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Push worker image na GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/projekt-worker:latest